export const workData = [
    {
        id: 1,
        slug: "echoza",
        title: "Echoza",
        category: "app",
        img: "/assets/echoza-mockup.png",
        themeColor: "#7c3aed",
        detailsTitle: "Audio/Video Enhancement App",
        detailsDesc: "A feature-rich Flutter app with Firebase backend where users record or upload audio/videos and apply real-time noise suppression and voice enhancement. Includes history tracking, profile management, premium features, and Google Ads.",
        created: "Spring 2025",
        technologies: "Flutter, Firebase",
        role: "Full Stack Developer",
        link: "https://github.com/SyedMuaarij-Nadeem/Echoza"
    },
    {
        id: 2,
        slug: "easetocure",
        title: "Ease to Cure",
        category: "web",
        img: "/assets/easetocure-mockup.png",
        themeColor: "#059669",
        detailsTitle: "Medicinal Information System",
        detailsDesc: "A web-based medicinal information system using HTML, CSS, JS, Node.js, and Firebase. Users can search medicines, view health charts, and leave reviews, while admins manage data, feedback, and authentication.",
        created: "Spring 2025",
        technologies: "Node.js, Firebase",
        role: "Full Stack Developer",
        link: "https://github.com/SyedMuaarij-Nadeem/EaseToCure"
    },
    {
        id: 3,
        slug: "primalforce",
        title: "Primal Force",
        category: "web",
        img: "/assets/primalForce.png",
        themeColor: "#dc2626",
        detailsTitle: "Gym Website",
        detailsDesc: "A 3D animated Gym website made using React, Three js, GSAP. Features immersive 3D models, scroll-triggered animations, and a premium dark red fitness aesthetic.",
        created: "Spring 2026",
        technologies: "React, Three.js, GSAP",
        role: "Full Stack Developer",
        link: "https://github.com/SyedMuaarij-Nadeem/primalForce"
    },
    {
        id: 4,
        slug: "travellingdiary",
        title: "Travelling Diary",
        category: "app",
        img: "/assets/travelDia-mockup.png",
        themeColor: "#2563eb",
        detailsTitle: "Travel Planning Application",
        detailsDesc: "A JavaFX GUI-based travel planner using OOP concepts where users can explore cities, find tourist spots, restaurants, and hotels with detailed info, images, and reviews. Great for planning trips interactively.",
        created: "Fall 2023",
        technologies: "Java, JavaFX",
        role: "Developer",
        link: "https://github.com/SyedMuaarij-Nadeem/TravellingDiary"
    },
    {
        id: 5,
        slug: "easetocure-ui",
        title: "EaseToCure - UI/UX Design",
        category: "design",
        img: "/assets/easetocure-ui-mocukup.png",
        themeColor: "#0891b2",
        detailsTitle: "Medicinal Information System UI",
        detailsDesc: "Figma design system for the EaseToCure web platform including responsive layouts, medication search interface, health chart visualizations, and admin dashboard components with dark/light mode variants and accessibility considerations.",
        created: "Fall 2024",
        tools: "Figma, Adobe XD",
        role: "UI Designer",
        link: "https://www.figma.com/design/0T1Wv2y8em9oUfWidJIyGH/EaseToCure?node-id=0-1&p=f&t=jNvq60FDTjHL7OBw-0"
    },
    {
        id: 6,
        slug: "harvesthustle",
        title: "Harvest Hustle",
        category: "app",
        img: "/assets/harvest-mockup.png",
        themeColor: "#d97706",
        detailsTitle: "Console-based Game",
        detailsDesc: "A C++ console-based game utilizing Data Structures and Algorithms like trees and linked lists. Players navigate levels of increasing difficulty, harvesting points in either quick play or adventure mode.",
        created: "Spring 2024",
        technologies: "C++, Data Structures",
        role: "Developer",
        link: "https://github.com/SyedMuaarij-Nadeem/HarvestHustle"
    },
    {
        id: 7,
        slug: "portfolio-template",
        title: "Responsive Portfolio Template",
        category: "web",
        img: "/assets/portfolio-temp-mockup.png",
        themeColor: "#7c3aed",
        detailsTitle: "Mobile & Desktop Portfolio",
        detailsDesc: "A fully responsive portfolio template built with pure HTML, CSS, and JavaScript. Features mobile-first design, adaptive layouts, CSS animations, and no framework dependencies. Works perfectly on all devices from smartphones to desktop.",
        created: "Summer 2024",
        technologies: "HTML5, CSS3, Vanilla JS",
        role: "Developer",
        link: "https://github.com/SyedMuaarij-Nadeem/PortfolioTemplate"
    },
    {
        id: 8,
        slug: "echoza-ui",
        title: "Echoza - UI/UX Design",
        category: "design",
        img: "/assets/echoza-ui-mockup.png",
        themeColor: "#9333ea",
        detailsTitle: "Audio/Video Enhancement App UI",
        detailsDesc: "A comprehensive Figma design for the Echoza mobile application featuring modern UI components, intuitive navigation flow, and interactive prototypes showcasing the audio enhancement features, user profiles, and premium subscription screens.",
        created: "Winter 2024",
        tools: "Figma, Adobe Illustrator",
        role: "UI/UX Designer",
        link: "https://www.figma.com/design/uLgGksNWTUeAGKQtTAqDDo/Echoza?node-id=0-1&p=f&t=R9WXCvXL1JHI7fAL-0"
    },
    {
        id: 9,
        slug: "hms",
        title: "Hotel Management System",
        category: "app",
        img: "/assets/hms-mockup.png",
        themeColor: "#1d4ed8",
        detailsTitle: "Hotel Management System",
        detailsDesc: "A robust SQL-based system covering all hotel operations including guest check-ins, room management, staff records, services, orders, and billing. It demonstrates core database design and query implementation.",
        created: "Fall 2024",
        technologies: "SQL, Database Design",
        role: "Database Developer",
        link: "https://github.com/SyedMuaarij-Nadeem/HMS-Hotel-Management-System"
    },
    {
        id: 10,
        slug: "artisan",
        title: "ARtisan",
        category: "web",
        img: "/assets/artisan-mockup.png",
        themeColor: "#8b5cf6",
        detailsTitle: "AI & WebAR E-Commerce Platform",
        detailsDesc: "A cutting-edge, web-based e-commerce solution addressing the spatial imagination gap. Integrates Generative AI for customized furniture and decor creation with immersive WebAR (Augmented Reality) to allow users to virtually place, scale, and rotate 3D products in their actual environment in real-time before purchase.",
        created: "Spring 2026",
        technologies: "React.js, Three.js, WebXR, GenAI API, Node.js",
        role: "Full Stack & AR Developer",
        link: "https://github.com/SyedMuaarij-Nadeem/ARtisan"
    },
    {
        id: 11,
        slug: "valors-quest",
        title: "Valor's Quest",
        category: "app",
        img: "/assets/valorsquest-mockup.png",
        themeColor: "#16a34a",
        detailsTitle: "3D Dungeon Escape Adventure",
        detailsDesc: "An atmospheric 3D adventure game created in Unity. Players control a lone wizard who must explore dangerous, dark environments, collect hidden keys, and solve structural puzzles to escape while defending against deadly monster AI.",
        created: "Fall 2025",
        technologies: "Unity 3D, C#, Shader Graph, Post-Processing",
        role: "Game Developer & Level Designer",
        link: "https://github.com/SyedMuaarij-Nadeem/Valors_Quest"
    },
    {
        id: 12,
        slug: "hire-lawyers",
        title: "Hire Lawyers",
        category: "web",
        img: "/assets/hirelawyers-mockup.png",
        themeColor: "#1e40af",
        detailsTitle: "Legal Expert Consultation Portal",
        detailsDesc: "A complete double-sided marketplace platform connecting clients with legal professionals. Features advanced search algorithms to filter lawyers by specialty and location, direct consultation scheduling, profile management, and interactive booking dashboards for both clients and attorneys.",
        created: "Fall 2025",
        technologies: "React.js, Node.js, Express.js, MongoDB",
        role: "Full Stack Developer",
        link: "https://github.com/SyedMuaarij-Nadeem/Hire_Lawyers"
    },
    {
        id: 13,
        slug: "ochi-design",
        title: "Ochi Design-clone",
        category: "web",
        img: "/assets/ochiclone-mockup.png",
        themeColor: "#e2e8f0",
        detailsTitle: "Premium Animated Agency Showcase",
        detailsDesc: "An ultra-premium front-end interactive showcase inspired by the award-winning Ochi Design studio website. Features rich typography, pixel-perfect layout controls, advanced scroll-triggered visual sequences, fluid animations, and custom locomotive scrolling effects.",
        created: "Spring 2026",
        technologies: "React, Tailwind CSS, Framer Motion, Locomotive Scroll",
        role: "Frontend Developer",
        link: "https://github.com/SyedMuaarij-Nadeem/ochi-design"
    }
];
